# Generated by Django 4.2.6 on 2023-10-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0007_country_alter_airport_closest_big_city_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="closest_big_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airports",
                to="airport.city",
            ),
        ),
    ]
