# Generated by Django 4.2.6 on 2023-10-20 18:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("airport", "0008_alter_airport_closest_big_city"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airplane",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="airplanetype",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="airport",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="country",
            unique_together={("name",)},
        ),
        migrations.AlterUniqueTogether(
            name="jobposition",
            unique_together={("title",)},
        ),
    ]
